- name: remove rbd from fstab
  mount:
    path: /mnt/rbd
    state: absent

- name: umount rbd
  mount:
    path: /mnt/rbd
    state: unmounted

- name: unmap rbd
  shell: rbd unmap /dev/rbd0
  args:
    executable: /bin/bash
  ignore_errors: True
